- id: yage-detect-rust
  name: Detect non-encrypted secrets
  description: Detect non-encrypted secrets using yage
  entry: yage status
  language: rust
- id: yage-detect
  name: Detect non-encrypted secrets
  description: Detect non-encrypted secrets using yage
  entry: yage status
  language: system
- id: yage-encrypt
  name: Encrypt secrets
  description: Secrets secrets using yage
  entry: yage status
  language: rust
- id: yage-encrypt
  name: Encrypt secrets
  description: Secrets secrets using yage
  entry: yage status
  language: system
