[package]
name = "yage"
version = "0.1.0"
edition = "2021"
authors = ["Gaëtan Lehmann <gaetan.lehmann@gmail.com>"]
description = "A simple tool to manage encrypted secrets in YAML files with age encryption"
readme = "README.md"
repository = "https://github.com/glehmann/ocli.git"
homepage = "https://github.com/glehmann/ocli.git"
documentation = "https://docs.rs/ocli/latest/ocli/"
license = "MIT"
keywords = ["secret management", "yaml", "encryption", "cli", "age"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = "0.9.2"
base64 = "0.21.7"
clap = { version = "4.4.18", features = ["derive", "env", "wrap_help"] }
clap-markdown = "0.1.3"
clap-verbosity-flag = "2.1.2"
clap_complete = "4.4.10"
log = "0.4.20"
ocli = "0.1.1"
serde_yaml = "0.9.31"
substring = "1.4.5"
tempfile = "3.9.0"
thiserror = "1.0.56"
treediff = { git = "https://github.com/glehmann/treediff-rs.git", branch = "serde-yaml-09", features = ["with-serde-yaml"] }

[build-dependencies]
clap = { version = "4.4.18", features = ["derive", "env", "wrap_help"] }
clap-markdown = "0.1.3"
clap-verbosity-flag = "2.1.2"
clap_mangen = "0.2.18"

[profile.release]
strip = "symbols"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
