[package]
name = "yage"
version = "0.1.0"
edition = "2021"
authors = ["Gaëtan Lehmann <gaetan.lehmann@gmail.com>"]
description = "A simple tool to manage encrypted secrets in YAML files."
readme = "README.md"
repository = "https://github.com/glehmann/ocli.git"
homepage = "https://github.com/glehmann/ocli.git"
documentation = "https://docs.rs/ocli/latest/ocli/"
license = "MIT"
keywords = ["secret management", "yaml", "encryption", "cli", "age"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = "0.9.2"
clap = { version = "4.4.18", features = ["derive", "env"] }
clap-verbosity-flag = "2.1.2"
log = "0.4.20"
ocli = "0.1.1"
thiserror = "1.0.56"
