name: docker

# Only do the release on x.y.z tags.
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CROSS_VERSION: v0.2.5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Install earthly
        uses: earthly/actions-setup@v1.0.4
        with:
          version: 0.8.3
          use-cache: "false"

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the images
        run: earthly --allow-privileged --push --no-output +docker-multiplatform --tag=${{ github.ref_name }}
